FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt install -y \
    build-essential \
    git \
    bc \
    bison \
    flex \
    libssl-dev \
    libelf-dev \
    dwarves \
    clang \
    llvm \
    lld \
    gcc \
    g++ \
    make \
    cmake \
    python3 \
    python3-pip \
    qemu-system-x86 \
    qemu-utils \
    gdb \
    ccache \
    rsync \
    file \
    vim \
    tree \
    qemu-system-aarch64 \
    && rm -rf /var/lib/apt/lists/*

ENV CCACHE_DIR=/ccache
ENV PATH="/usr/lib/ccache:$PATH"

WORKDIR /workspace
